### ISSUE TITLE
kernel build faild

### ISSUE THREAD

**Issue by balah2o** [UnicomAndroid/Android-Builder#1]
i tried to use github action to build a kernel with kernelsu for my device. it faild. i don't know how to solve the problem and i need some help.
source kernel: https://github.com/thetanmaygupta/kernel_xiaomi_light
kernel defconfig: k6833v1_64_defconfig
toolchains, enableCcache, params, AnyKernel3, enableLXC: default
enableKernelSU: true
config: https://github.com/balah2o/Android-Builder/blob/main/Kernel/configs/light.config.json
action log: https://github.com/balah2o/Android-Builder/actions/runs/6913929331/job/18811293444
error log: 
```
make[1]: *** [/home/runner/work/Android-Builder/Android-Builder/BalaKernel-withsu/Makefile:1174: arch/arm64/kernel] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      init/calibrate.o
  CC      init/init_task.o
  CC      init/version.o
  AR      init/mounts.o
  AR      init/built-in.o
make[1]: Leaving directory '/home/runner/work/Android-Builder/Android-Builder/out'
make: *** [Makefile:146: sub-make] Error 2
Error: Process completed with exit code 2.
```
<img width="1404" alt="15cb7ff36cd88255df4a5cc69ac4f847" src="https://github.com/DogDayAndroid/Android-Builder/assets/151156946/8b52ba6b-fd71-4160-abe3-fef266438127">

**Comment by easterNday** [comment]
Please give me other relevant information about the corresponding kernel, such as the system developed by the author using this kernel to facilitate the determination of the compilation tool chain.

What is certain is that the latest kernel commit affects compilation. After removing this update, it is most likely that the problem is caused by different versions of the compilation tool chain.
